[plugin]
name = "dokku-app-predeploy-tasks"
description = "Run arbitrary app tasks prior to dokku's deploy phase"
version = "0.1.0"
website_url = "https://github.com/michaelshobbs/dokku-app-predeploy-tasks"
[plugin.config]
